name: "Experiment_3"
cuda: True
seed: 0

environment:
  name: "CartPole-v1"

model:
  num_options: 4
  latent_dimension: 64
  termination_regularization: 0.01
  entropy_regularization: 0.01
  temperature: 1

training:
  num_transitions: 100000
  learning_rate: 0.0005
  discount_factor: 0.99
  epsilon:
    init_value: 1.0
    decay_mode: 'lin'
    milestones:
      15000: 0
  replay_buffer_length: 10000
  batch_size: 32
  freeze_interval: 200
  critic_replay_period: 4
  max_episode_length: 10000
