name: "rl-zoo-0"
cuda: True
cores: 8
seed: 1234

environment:
  name: "ALE/Pong-v5"
  object_centric: False
  reward_mode: env  # env, human, mixed
  prune_concept: default  # default or external: use pruned focusfile (from default 'focusfiles' dir or external 'baselines_focusfiles' dir. for custom pruning and or docker mount)
  exclude_properties: True  # exclude properties from feature vector
  framestack: 4  # ignored when object-centric (1 in that case)
  frameskip: 4  # ignored when object-centric (1 in that case)

model:  # if an existing model is reloaded, these parameters are ignored
  options_hierarchy: []  # e.g., [2, 4, 8] means 2 high-level, 4 mid-level, and 8 low-level options
  ppo:
    n_steps: 128
    n_epochs: 4
    batch_size: 256
    gamma: 0.99
    # gae_lambda: 0.95
    clip_range:  # clipping epsilon
      initial_value: 0.1
      schedule_type: linear
    vf_coef: 0.5
    ent_coef: 0.01
    clip_range_vf:
    normalize_advantage: True
    gae_lambda: 0.95

training:
  total_timesteps: 1e7
  learning_rate:  # Adam
    initial_value: 2.5e-4
    schedule_type: linear
  eval_frequency: 200000
