name: "rl-zoo-oc-human"
cuda: False
cores: 4
seed: 0

environment:
  name: "ALE/Pong-v5"
  object_centric: True
  reward_mode: human  # env, human, mixed
  prune_concept: default  # default or external: use pruned focusfile (from default 'focusfiles' dir or external 'baselines_focusfiles' dir. for custom pruning and or docker mount)
  exclude_properties: True  # exclude properties from feature vector
  framestack: 4
  frameskip: 1

model:  # if an existing model is reloaded, these parameters are ignored
  num_options: 1
  ppo:
    n_steps: 256
    n_epochs: 4
    batch_size: 256
    gamma: 0.99
    # gae_lambda: 0.95
    clip_range:  # clipping epsilon
      initial_value: 0.1
      schedule_type: linear
    vf_coef: 0.5
    ent_coef: 0.01
    clip_range_vf:
    normalize_advantage: True

training:
  total_timesteps: 1e6
  learning_rate:  # Adam
      initial_value: 0.001
      schedule_type: linear
